#!/usr/bin/env bash
# Script that sets the port 80
# Requirement: Nginx must be running and listening on port 80 of all the serer active IPv4  IPs
# Bug: sudo nginx status return 'not ruuning '; netstat -lpn does not show show  port 80
# solution : https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80
sudo sed -i "s/sites-enabled/ sitees-available/" /etc/nginx/nginx.conf
sudo service nginx restart